## V15
tesoreria_v15 = {   1: 'Comercio al por Menor',
                    2: 'Comercio al por Mayor',
                    3: 'NA',
                    4: 'Servicios Profesionales, Técnicos, Especializados y Personales',
                    5: 'Servicios de Alquiler y Administración de Bienes inmueble',
                    6: 'Servicios Educativos, Investigación, Médicos y de Asistencia social y de Asociaciones Civil y Religiosas',
                    7: 'Servicios Financieros, de Seguros y Fianzas',
                    8: 'Construcción',
                    9: 'Servicios de Reparación y Mantenimiento',
                    10: 'Servicios de Comunicaciones',
                    11: 'Servicios de Administración Pública, Defensa y Saneamiento',
                    12: 'Textiles, Prendas de Vestir e Industria de Cuero',
                    13: 'Transportes',
                    14: 'Restaurantes',
                    15: 'Servicios de Esparcimiento, Culturales, Recreativos y Deportivos',
                    16: 'Hoteles',
                    17: 'Papel y Productos de Papel, Imprentas y Editoriales',
                    18: 'Servicios de Alquiler y Administración de Bienes Inmueble',
                    19: 'Productos Alimenticios, Bebidas y Tabacos',
                    20: 'Otras Industrias Manufactureras',
                    21: 'Servicios Relacionados con la Agricultura, Ganadería, Construcción, Transportes, Financieros y Comercio',
                    22: 'Sustancias Químicas, Productos derivados del Petroleo, carbón, hule y plástico',
                    23: 'Industria de la Madera y Productos de la Madera',
                    24: 'Electricidad',
                    25: 'Captación, Potabilización y Distribución de Agua',
                    26: 'Agricultura, Ganadería y Caza',
                    27: 'Industrias Metálicas Básicas',
                    28: 'Productos Metálicos, Maquinaria y Equipo',
                    29: 'Carbón',
                    30: 'Petroleo y Gas Natural',
                    31: 'Pesca',
                    32: 'Productos Minerales no Metálicos, Excepto derivados del petroleo',
                    33: 'Extracción de Materiales Metálicos',
                    34: 'Extracción de Minerales no Metálicos',
                    35: 'Servicios de Organismos Internacionales',
                    36: 'Silvicultura'
                    }

## scian ---- descripcion
tesoreria_to_scian = {   1: ("46"),
                    2: ("431", "432", "433", "436", "434","435","436"),
                    4: ("54"),
                    5: ("532"),
                    6: ("61"),
                    7: ("52"),
                    8: ("237"),
                    9: ("811"), # Este es nuevo 811 Servicios de reparación y mantenimiento
                    10: ('517'), # Este es nuevo Telecomunicaciones
                    11: ("931"),
                    12: ("314", "315"),
                    13: ("485", "483", "481"),
                    14: ("722"),
                    15: ("71"),
                    16: ("721"),
                    17: ("322"),
                    18: ("53"),
                    19: ("311", "3121", "3122"),
                    20: ("339"),
                    21: ("488"),
                    22: ("325"),
                    23: ("321"),
                    24: ('2211'),
                    25: ("2213"),
                    26: ("111", "112", "114"),
                    27: ("331"),
                    28: ("333"),
                    29: ("324"),
                    30: ("211"),
                    31: ("114"),
                    32: ("327"),
                    33: ("212"),
                    34: ("212"),
                    35: ("932"),
                    36: ("113")
                    }

tesoreria_to_scian_array = {   1: ["46"],
                      2: ["431", "432", "433", "436", "434","435","436"],
                      4: ["54"],
                      5: ["532"],
                      6: ["61"],
                      7: ["52"],
                      8: ["237"],
                      9: ["811"], # Este es nuevo 811 Servicios de reparación y mantenimiento
                      10: ['517'], # Este es nuevo Telecomunicaciones
                      11: ["931"],
                      12: ["314", "315"],
                      13: ["485", "483", "481"],
                      14: ["722"],
                      15: ["71"], 
                      16: ["721"],
                      17: ["322"],
                      18: ["53"],
                      19: ["311", "3121", "3122"],
                      20: ["339"], 
                      21: ["488"],
                      22: ["325"],
                      23: ["321"],
                      24: ['2211'],
                      25: ["2213"],
                      26: ["111", "112", "114"],
                      27: ["331"],
                      28: ["333"],
                      29: ["324"],
                      30: ["211"],
                      31: ["114"],
                      32: ["327"],
                      33: ["212"],
                      34: ["212"],
                      35: ["932"],
                      36: ["113"]
                     }