
## sector_economico_2_2pos ---- descripcion_sector_economico_2

cw_sec_2_2pos_descrip = {"1" : "Agricultura",
                        "2" : "Ganadería",
                        "3" : "Silvicultura",
                        "4" : "Pesca",
                        "5" : "Caza",
                        "11" : "Extracción  y  beneficio de carbón mineral, grafito y minerales no metálicos; excepto sal",
                        "12" : "Exploración y extracción  de  petróleo crudo y gas natural (no incluye a Pemex)",
                        "13" : "Extracción y beneficio de minerales metálicos",
                        "14" : "Explotación de sal",
                        "20" : "Fabricación de alimentos",
                        "21" : "Elaboración de bebidas",
                        "22" : "Beneficio y fabricación de productos de tabaco",
                        "23" : "Industria textil",
                        "24" : "Confección de prendas de vestir y otros artículos confeccionados con textiles y otros materiales; excepto calzado",
                        "25" : "Fabricación de  calzado e industria del cuero",
                        "26" : "Industria y productos de madera y corcho; excepto muebles",
                        "27" : "Fabricación y reparación de muebles de madera y sus partes; excepto los de metal y plástico moldeado",
                        "28" : "Industria del papel",
                        "29" : "Industrias editorial, de impresión y conexas",
                        "30" : "Industria química",
                        "31" : "Refinación del petróleo y derivados del carbón mineral (no incluye Pemex)",
                        "32" : "Fabricación de productos de hule y plástico",
                        "33" : "Fabricación de productos de minerales no metálicos;  excepto del petróleo y del carbón mineral",
                        "34" : "Industrias metálicas básicas",
                        "35" : "Fabricación de productos metálicos; excepto maquinaria y equipo",
                        "36" : "Fabricación, ensamble y reparación de maquinaria, equipo y sus partes; excepto los eléctricos",
                        "37" : "Fabricación y ensamble de maquinaria, equipos, aparatos, accesorios y artículos eléctricos, electrónicos y sus partes",
                        "38" : "Construcción, reconstrucción y ensamble de equipo de transporte y sus partes",
                        "39" : "Otras industrias manufactureras",                    
                        "41" : "Construcción de edificaciones y de obras de ingeniería civil",
                        "42" : "Trabajos realizados por contratistas especializados",                                                 
                        "50" : "Generación, transmisión y distribución de energía eléctrica",                                                                 
                        "51" : "Captación y suministro de agua potable",                                             
                        "61" : "Compraventa de alimentos, bebidas y productos del tabaco",                                                                         
                        "62" : "Compraventa de prendas de vestir y otros artículos de uso personal",
                        "63" : "Compraventa de artículos para el hogar",                      
                        "64" : "Compraventa en tiendas de autoservicio y de departamentos especializados por línea de mercancías",
                        "65" : "Compraventa de gases, combustibles y lubricantes",
                        "66" : "Compraventa de materias primas, materiales y auxiliares",                                               
                        "67" : "Compraventa de maquinaria, equipo, instrumentos, aparatos, herramientas;  sus refacciones y accesorios",
                        "68" : "Compraventa de equipo de transporte; sus refacciones y accesorios",
                        "69" : "Compraventa de inmuebles y artículos diversos",
                        "71" : "Transporte terrestre",                                      
                        "72" : "Transporte por agua",                                                                                                                      
                        "73" : "Transporte aéreo",                                                                          
                        "74" : "Servicios conexos al transporte",
                        "75" : "Servicios relacionados con el transporte en general",
                        "76" : "Comunicaciones",                                                                                       
                        "81" : "Servicios financieros y de seguros (bancos, financieras, compañías de seguros, etc.)",
                        "82" : "Servicios colaterales a las instituciones financieras y de seguros",                                         
                        "83" : "Servicios relacionados con inmuebles",    
                        "84" : "Servicios profesionales y técnicos",                                                                                                        
                        "85" : "Servicios de alquiler; excepto de inmuebles",                                                                                                    
                        "86" : "Servicios de alojamiento temporal",                                                                                      
                        "87" : "Preparación y servicio de alimentos y bebidas",                                                                                       
                        "88" : "Servicios recreativos y de esparcimiento",                                                                                
                        "89" : "Servicios personales para el hogar y diversos",
                        "91" : "Servicios de enseñanza, investigación científica y difusión cultural",
                        "92" : "Servicios médicos, asistencia social y veterinarios",                                                                                 
                        "93" : "Agrupaciones mercantiles, profesionales, cívicas, políticas, laborales y religiosas",                                                 
                        "94" : "Servicios de administración pública y seguridad social",                                          
                        "99" : "Servicios de organizaciones internacionales y otros organismos extraterritoriales"}


## scian ---- descripcion
cw_scian_descrip = {
                        "111":"Agricultura" ,
                        "112":"Cría y explotación de animales" ,
                        "113":"Aprovechamiento foresta" ,
                        "114":"Pesca, caza y captura" ,
                        "114":"Pesca, caza y captura" ,
                        "212":"Minería de minerales metálicos y no metálicos, excepto petróleo y gas" ,
                        "211":"Extracción de petróleo y gas" ,
                        "213":"Servicios relacionados con la minería" ,
                        "311":"Industria alimentaria" ,
                        "311":"Industria alimentaria" ,
                        "3121":"Industria de las bebidas" ,
                        "3122":"Industria del tabaco" ,
                        "314":"Fabricación de productos textiles, excepto prendas de vestir" ,
                        "315":"Fabricación de prendas de vestir" ,
                        "3162":"Fabricación de calzado" ,
                        "321":"Industria de la madera" ,
                        "8114":"Reparación y mantenimiento de artículos para el hogar y personales" ,
                        "322":"Industria del papel" ,
                        "323":"Impresión e industrias conexas" ,
                        "325":"Industria química" ,
                        "324":"Fabricación de productos derivados del petróleo y del carbón" ,
                        "326":"Industria del plástico y del hule" ,
                        "327":"Fabricación de productos a base de minerales no metálicos" ,
                        "331":"Industrias metálicas básicas" ,
                        "332":"Fabricación de productos metálicos" ,
                        "333":"Fabricación de maquinaria y equipo" ,
                        "335":"Fabricación de accesorios, aparatos eléctricos y equipo de generación de energía eléctrica" ,
                        "336":"Fabricación de equipo de transporte" ,
                        "339":"Otras industrias manufactureras" ,
                        "237":"Construcción de obras de ingeniería civil" ,
                        "238":"Trabajos especializados para la construcción" ,
                        "2211":"Generación, transmisión, distribución y comercialización de energía eléctrica" ,
                        "2213":"Captación, tratamiento y suministro de agua" ,
                        "431":"Comercio al por mayor de abarrotes, alimentos, bebidas, hielo y tabaco" ,
                        "432":"Comercio al por mayor de productos textiles y calzado" ,
                        "433":"Comercio al por mayor de productos farmacéuticos, de perfumería, artículos para el esparcimiento, electrodomésticos menores y aparatos de línea blanca" ,
                        "433":"Comercio al por mayor de productos farmacéuticos, de perfumería, artículos para el esparcimiento, electrodomésticos menores y aparatos de línea blanca" ,
                        "436":"Comercio al por mayor de camiones y de partes y refacciones nuevas para automóviles, camionetas y camiones" ,
                        "434":"Comercio al por mayor de materias primas agropecuarias y forestales, para la industria, y materiales de desecho" ,
                        "435":"Comercio al por mayor de maquinaria, equipo y mobiliario para actividades agropecuarias, industriales, de servicios y comerciales, y de otra maquinaria y equipo de uso general" ,
                        "436":"Comercio al por mayor de camiones y de partes y refacciones nuevas para automóviles, camionetas y camiones" ,
                        "435":"Comercio al por mayor de maquinaria, equipo y mobiliario para actividades agropecuarias, industriales, de servicios y comerciales, y de otra maquinaria y equipo de uso general" ,
                        "485":"Transporte terrestre de pasajeros, excepto por ferrocarril" ,
                        "483":"Transporte por agua" ,
                        "481":"Transporte aéreo" ,
                        "488":"Servicios relacionados con el transporte" ,
                        "488":"Servicios relacionados con el transporte" ,
                        "51":"Información en medios masivos" ,
                        "52":"Servicios financieros y de seguros" ,
                        "52":"Servicios financieros y de seguros" ,
                        "53":"Servicios inmobiliarios y de alquiler de bienes muebles e intangibles" ,
                        "54":"Servicios profesionales, científicos y técnicos" ,
                        "532":"Servicios de alquiler de bienes muebles" ,
                        "721":"Servicios de alojamiento temporal" ,
                        "722":"Servicios de preparación de alimentos y bebidas" ,
                        "71":"Servicios de esparcimiento culturales y deportivos, y otros servicios recreativos" ,
                        "814":"Hogares con empleados domésticos" ,
                        "61":"Servicios educativos" ,
                        "62":"Servicios de salud y de asistencia social" ,
                        "813":"Asociaciones y organizaciones" ,
                        "931":"Actividades legislativas, gubernamentales y de impartición de justicia" ,
                        "932":"Organismos internacionales y extraterritoriales" 
}

## sector_economico_2_2pos --- scian
cw_imss_scian = {
                        "1":"111" ,
                        "2":"112" ,
                        "3":"113" ,
                        "4":"114" ,
                        "5":"114" ,
                        "11":"212" ,
                        "12":"211" ,
                        "13":"213" ,
                        "14":"311" ,
                        "20":"311" ,
                        "21":"3121" ,
                        "22":"3122" ,
                        "23":"314" ,
                        "24":"315" ,
                        "25":"3162" ,
                        "26":"321" ,
                        "27":"8114" ,
                        "28":"322" ,
                        "29":"323" ,
                        "30":"325" ,
                        "31":"324" ,
                        "32":"326" ,
                        "33":"327" ,
                        "34":"331" ,
                        "35":"332" ,
                        "36":"333" ,
                        "37":"335" ,
                        "38":"336" ,
                        "39":"339" ,
                        "41":"237" ,
                        "42":"238" ,
                        "50":"2211" ,
                        "51":"2213" ,
                        "61":"431" ,
                        "62":"432" ,
                        "63":"433" ,
                        "64":"433" ,
                        "65":"436" ,
                        "66":"434" ,
                        "67":"435" ,
                        "68":"436" ,
                        "69":"435" ,
                        "71":"485" ,
                        "72":"483" ,
                        "73":"481" ,
                        "74":"488" ,
                        "75":"488" ,
                        "76":"51" ,
                        "81":"52" ,
                        "82":"52" ,
                        "83":"53" ,
                        "84":"54" ,
                        "85":"532" ,
                        "86":"721" ,
                        "87":"722" ,
                        "88":"71" ,
                        "89":"814" ,
                        "91":"61" ,
                        "92":"62" ,
                        "93":"813" ,
                        "94":"931" ,
                        "99":"932" 
}